version: "3.7"

services:
  redis:
    image: redis
    container_name: notfredis
    expose:
      - 6379
  server:
        build:
            context: ./notifications/notif-server/
        ports:
        - "3312:3322"
        container_name: server
        links:
          - redis
        environment:
          - REDIS_URL=redis://notfredis
  client:
        build:
            context: ./notifications/notif-client/
        ports:
        - "3000:3000"
        container_name: client
        
  